### ISSUE TITLE
Application version detail Page

### ISSUE THREAD

**Issue by milaendo** [KillahDillah/wireframes#1]
- Needs title to be fixed
- bootstrap button needs to replace current button
- footer needs to be completed

**Comment by KillahDillah** [comment]
![screen shot 2018-09-12 at 10 34 06 am](https://user-images.githubusercontent.com/29666170/45442640-695f0b00-b677-11e8-8f95-9ba8229cf106.png)

**Comment by milaendo** [comment]
"packages installed" needs to be the same size as "current stack"
