### ISSUE TITLE
group-members.html

### ISSUE THREAD

**Issue by milaendo** [KillahDillah/wireframes#7]
![screen shot 2018-09-12 at 9 52 07 am](https://user-images.githubusercontent.com/29641725/45440586-8a246200-b671-11e8-8f1e-b8846d40eb88.png)
- this bar needs to be a multiselect placeholder and even spaced between label and button
- needs pagination placeholder under data table 
- more of a top margin between the table and the multiselect

**Comment by KillahDillah** [comment]
![screen shot 2018-09-12 at 11 17 13 am](https://user-images.githubusercontent.com/29666170/45444846-7121ae00-b67d-11e8-9bb7-c87b6db94b17.png)

**Comment by milaendo** [comment]
more spacing is needed between the label and the multiselect

**Comment by KillahDillah** [comment]
![screen shot 2018-09-12 at 11 22 26 am](https://user-images.githubusercontent.com/29666170/45445086-26546600-b67e-11e8-83c4-0ed53c800d02.png)
